language: python

python:
  - 2.7
  - 3.3
  - pypy

install:
  - pip install --use-mirrors -r test-requires.txt

script:
  - python test.py

after_success:
  - pip install pep8 pyflakes
  - pep8 *.py
  - pyflakes *.py
  - pep8 pp/*.py
  - pyflakes pp/*.py

matrix:
  allow_failures:
    - python: 3.3
